CREATE TABLE contabilidade2024 (
    DATA DATE NOT NULL,
    REG_ANS INT NOT NULL,
    CD_CONTA_CONTABIL VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    VL_SALDO_INICIAL DECIMAL(15,2) NOT NULL,
    VL_SALDO_FINAL DECIMAL(15,2) NOT NULL,
    PRIMARY KEY (DATA, REG_ANS, CD_CONTA_CONTABIL)
);